// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi0vclr1RtMy6T0whWKZA5c59vg3Pt-lk',
    appId: '1:191172132292:web:23967b6de2f65cf309b891',
    messagingSenderId: '191172132292',
    projectId: 'my-first-project-54194',
    authDomain: 'my-first-project-54194.firebaseapp.com',
    storageBucket: 'my-first-project-54194.firebasestorage.app',
    measurementId: 'G-434GTYQ39B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK4S13l82mYyxyJtMCpsxWrLtY2yWzuCA',
    appId: '1:191172132292:android:01a9a8a383d3005e09b891',
    messagingSenderId: '191172132292',
    projectId: 'my-first-project-54194',
    storageBucket: 'my-first-project-54194.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9vAUoAhnqN7OG108HVcNDdrOeBCnyQVw',
    appId: '1:191172132292:ios:91b6ff0f8c3774cd09b891',
    messagingSenderId: '191172132292',
    projectId: 'my-first-project-54194',
    storageBucket: 'my-first-project-54194.firebasestorage.app',
    iosBundleId: 'com.example.pilem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9vAUoAhnqN7OG108HVcNDdrOeBCnyQVw',
    appId: '1:191172132292:ios:91b6ff0f8c3774cd09b891',
    messagingSenderId: '191172132292',
    projectId: 'my-first-project-54194',
    storageBucket: 'my-first-project-54194.firebasestorage.app',
    iosBundleId: 'com.example.pilem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBi0vclr1RtMy6T0whWKZA5c59vg3Pt-lk',
    appId: '1:191172132292:web:22e71ebc185165f909b891',
    messagingSenderId: '191172132292',
    projectId: 'my-first-project-54194',
    authDomain: 'my-first-project-54194.firebaseapp.com',
    storageBucket: 'my-first-project-54194.firebasestorage.app',
    measurementId: 'G-HD10D037QT',
  );
}
